ALTER TABLE healthcare
RENAME COLUMN ï»¿Name TO NAME;
COMMIT;

SELECT * FROM healthcare;

-- What is the distribution of patients by gender?
SELECT Gender,COUNT(*) AS Total_Patient
FROM healthcare
GROUP BY Gender;

-- What are the top 5 most common medical conditions?
SELECT `Medical Condition`,COUNT(*) AS commonly FROM healthcare
GROUP BY `Medical Condition`
ORDER BY commonly DESC
LIMIT 5;

-- What is the total revenue generated by each hospital?
SELECT Hospital,ROUND(SUM(`Billing Amount`),2) AS Total_Revenue FROM healthcare
GROUP BY Hospital
ORDER BY Total_Revenue DESC;

-- What is the average hospital stay duration for patients?
SELECT ROUND(AVG(datediff(STR_TO_DATE(`Discharge Date`,'%Y-%m-%d'),STR_TO_DATE(`Date of Admission`,'%Y-%m-%d'))),2) AS Average_Stay
FROM healthcare
WHERE `Discharge Date` IS NOT NULL 
AND
`Date of Admission` IS NOT NULL;

-- Which insurance provider has the highest total billing amount?
SELECT `Insurance Provider`,ROUND(SUM(`Billing Amount`),2) AS Total_bill
FROM healthcare
GROUP BY `Insurance Provider`
ORDER BY Total_bill DESC
LIMIT 1;

-- Which medical condition generates the highest average billing amount?
SELECT `Medical Condition`,ROUND(AVG(`Billing Amount`),2) AS Average_bill FROM healthcare
GROUP BY `Medical Condition`
ORDER BY Average_bill DESC
LIMIT 1;

-- Find the medical condition(s) whose average billing amount is higher than the overall average billing amount.
SELECT `Medical Condition` FROM healthcare
GROUP BY `Medical Condition`
HAVING AVG(`Billing Amount`)>(SELECT ROUND(AVG(`Billing Amount`),2) FROM healthcare);

-- Create a view to show total and average billing amount for each hospital, and then retrieve the top 3 hospitals based on total billing.
CREATE VIEW DETAIL
AS 
SELECT Hospital,ROUND(SUM(`Billing Amount`),2) AS TOTAL,ROUND(AVG(`Billing Amount`),2) AS AVG_BILL
FROM healthcare 
GROUP BY Hospital;

SELECT * FROM DETAIL
ORDER BY TOTAL DESC
LIMIT 3;

-- Create a stored procedure that takes admission type as input and returns total number of patients and average billing amount for that type.
DELIMITER //
CREATE PROCEDURE CASES (IN admission varchar(20))
BEGIN 
SELECT COUNT(*) AS TOTAL_PATIENT,ROUND(AVG(`Billing Amount`),2) AS AVERAGE_BILLING_AMOUNT
FROM healthcare
WHERE `Admission Type`=admission;
END //
DELIMITER ;

CALL CASES('Urgent');

-- Rank doctors based on total billing amount generated and display their rank along with doctor name and total revenue.
SELECT Doctor,ROUND(SUM(`Billing Amount`),2) AS TOTAL_REVENUE,
RANK() OVER (ORDER BY SUM(`Billing Amount`) DESC) 
FROM healthcare
GROUP BY Doctor;

-- Using a CTE, calculate average hospital stay duration and find patients whose stay duration is greater than the average.
WITH DETAILS AS
(
SELECT AVG(DATEDIFF(STR_TO_DATE(`Discharge Date`,'%Y-%m-%d'),STR_TO_DATE(`Date of Admission`,'%Y-%m-%d'))) AS AVERAGE_STAY_DURATION
FROM healthcare
)
SELECT * FROM healthcare,Details
WHERE DATEDIFF(STR_TO_DATE(`Discharge Date`,'%Y-%m-%d'),STR_TO_DATE(`Date of Admission`,'%Y-%m-%d'))>DETAILS.AVERAGE_STAY_DURATION;
